spring:
  # Configura√ß√µes Padr√£o (Usadas localmente se nenhum profile estiver ativo)
  datasource:
    # Use as configura√ß√µes do localhost como fallback
    url: jdbc:postgresql://localhost:5432/carehub_db
    username: postgres
    password: CareHub2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Mantemos 'update' em desenvolvimento
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configura√ß√µes do Profile de PRODU√á√ÉO (Ativado no Render.com)
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # üö® FOR√áA a leitura da vari√°vel de ambiente, com um valor default vazio.
    url: ${DATABASE_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # Esconde o SQL no console de produ√ß√£o
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect