spring:
  # Configura√ß√µes Padr√£o (Usadas localmente se nenhum profile estiver ativo)
  datasource:
    # Use as configura√ß√µes do localhost como fallback
    url: jdbc:postgresql://localhost:5432/carehub_db
    username: postgres
    password: CareHub2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Mantemos 'update' em desenvolvimento
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configura√ß√µes do Profile de PRODU√á√ÉO (Ativado no Render.com)
---
spring:
  config:
    activate:
      on-profile: prod

  # üö® Mude a inje√ß√£o para o formato de "propriedades" dentro do bloco do perfil
  datasource:
    # A URL est√° sendo injetada, mas pode precisar dos campos user/pass fora da URL
    url: ${DATABASE_URL}
    # ADICIONE estas linhas de inje√ß√£o, mesmo que a URL j√° contenha os dados.
    # Isso √© necess√°rio porque o Spring Boot precisa dos campos de usu√°rio e senha separados
    # para usar o pool de conex√µes (HikariCP).
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false # Esconde o SQL no console de produ√ß√£o
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect