spring:
  # Configurações Padrão (Usadas localmente se nenhum profile estiver ativo)
  datasource:
    # Use as configurações do localhost como fallback
    url: postgresql://admin:OcL8T8iDAzMUufmaMvq1ezaiQIJg58jp@dpg-d4eav0euk2gs739ek7vg-a.oregon-postgres.render.com/carehub_bd
    username: admin
    password: OcL8T8iDAzMUufmaMvq1ezaiQIJg58jp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Mantemos 'update' em desenvolvimento
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configurações do Profile de PRODUÇÃO (Ativado no Render.com)
---
spring:
  config:
    activate:
      on-profile: prod # Define o profile como 'prod'
  datasource:
    # O Render injetará a URL do banco de dados de produção nesta variável
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # MUITO IMPORTANTE: Em produção, o 'ddl-auto' deve ser 'validate' ou 'none'
      # para evitar que o Hibernate tente alterar o esquema do DB automaticamente.
      ddl-auto: validate
    show-sql: false # Esconde o SQL no console de produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect